### ISSUE TITLE
Dependencies exceed the size 2M limit of the wechat miniprogram

### ISSUE THREAD

**Issue by puma007** [tensorflow/tfjs-wechat#13]
TensorFlow.js version：1.2.2
tfjs-wechat plugin version：0.0.5

Because my model is converted from keras, I need to use tf.loadLayersModel in a single javascript file， the package depends on the following:
"dependencies": {
     "@tensorflow/tfjs-core": "1.2.2",
    "@tensorflow/tfjs-layers": "1.2.2",
     "fetch-wechat": "0.0.3"
   }
But when compiling and preview upload, it will prompt a size limit exceeding 2M.

**Comment by pyu10055** [comment]
@puma007 The issue is wechat js minimization is good enough, we are looking into a solution that expose only the minimized version of our lib to wechat npm build tool.
To work around now, you can manually copy the minimized version of tfjs-core and tfjs-layers to miniprogram_npm directory.

```
cp node_modules/\@tensorflow/tfjs-core/dist/tf-core.min.js miniprogram_npm/\@tensorflow/tfjs-core/index.js
cp node_modules/\@tensorflow/tfjs-layers/dist/tf-layers.min.js miniprogram_npm/\@tensorflow/tfjs-layers/index.js
```

This should only require around 700KB, please let me know if that works for you.

**Comment by puma007** [comment]
@pyu10055 Thank you very much! Manually copy the js file of minimized version as you said,that work fine!

**Comment by pyu10055** [comment]
Great. Once TFJS 1.2.4 version is released, you don’t need to manually copy the files any more.

**Comment by puma007** [comment]
@pyu10055 Awesome! Great work！

**Comment by pyu10055** [comment]
@puma007 Elise told me that you have encountered other issues, feel free to report them here. thanks.
