### ISSUE TITLE
Error: The dtype of dict['image_tensor'] provided in model.execute(dict) must be int32, but was float32

### ISSUE THREAD

**Issue by 2H0U** [tensorflow/tfjs-wechat#63]
其实我已经解决了，只是想对这个问题补充一点。我按照[这个方法](https://stackoverflow.com/questions/61036180/tensorflowjs-tfjs-error-the-dtype-of-dict)做完后还是报同样的错。原因是，这个方法只把load函数中的tf.zeros从float改为int32，实际上infer这个函数里的batched也需要同样的转换。我把return img.expandDims(0)改成return img.expandDims(0).asType('int32')，问题就解决了。希望能有所帮助。

**Comment by pyu10055** [comment]
@2H0U thanks for reporting, what is the version of tfjs you are using?

**Comment by 2H0U** [comment]
我所用到的版本是：core v1.7.2, converter v1.7.2, coco-ssd v2.0.2, tfjs-wechat-plugin v0.0.9

**Comment by pyu10055** [comment]
hmm, this is weird, I ran the stackoverflow example, it does not have the problem you described.  since fromPixels() return 'int32' dtype and img.expandDims(0) should not change the dtype of the tensor.unless you are passing the tensor to infer() method with the 'float32' dtype. Please help to check that, if so, you should update the tensor to 'int32' dtype.

**Comment by 2H0U** [comment]
确实是我输入的tensor有问题，实在不好意思。
